### ISSUE TITLE
RunTimeError: Error(s) in loading state_dict for RobertaForSequenceClassification

### ISSUE THREAD

**Issue by greenunknown** [openai/gpt-2-output-dataset#28]
I get the following error after trying to run 

```
pip install -r requirements.txt
python -m detector.server detector-base.pt
```

Error: 
```
RuntimeError: Error(s) in loading state_dict for RobertaForSequenceClassification:
        Missing key(s) in state_dict: "roberta.embeddings.position_ids".
        Unexpected key(s) in state_dict: "roberta.pooler.dense.weight", "roberta.pooler.dense.bias"
```
        
I'm not sure if there was a change between the google version of the Roberta weights or the azure version of the weights.

Thanks for the help!

**Comment by jongwook** [comment]
Hi, it's our bad that we didn't properly specify the dependency versions. Could you try with `transformer==2.9.1` and see if that loads properly?

**Comment by greenunknown** [comment]
Thank you @jongwook ! Changing, in the `requirements.txt`,  the `transformers>=2.0.0` to `transformers==2.9.1` resolved the issue.

**Comment by BelowzeroA** [comment]
Following your advice I installed `transformers==2.9.1` but after that the next issue popped up:
```
from transformers import RobertaForSequenceClassification, RobertaTokenizer
ImportError: cannot import name 'RobertaForSequenceClassification' from 'transformers'
```

**Comment by crazoter** [comment]
@BelowzeroA Did you manage to resolve this? The fix worked for me on Google Colab, but I encountered your issue when I tried the same fix on a fresh anaconda environment on a Windows 10 device.

**Comment by Yorko** [comment]
Made it work with Python 3.8, transformers 2.9.1, and tokenizers 0.7.0. 

FYI I'm using poetry and had to run the following:  
- `poetry env use <PATH_TO_python3.8>` (can be looked up running `which python3.8`)
- `poetry install`
- `poetry run python -m detector.server <PATH_TO_CKPT_detector-base.pt>`

My `pyproject.toml` file is the following:
```
[tool.poetry]
name = "gpt-2-output-dataset"
version = "0.1.0"
description = "GPT-2 output detector"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8.0"
transformers = "2.9.1"
fire = "^0.2.1"
requests = "^2.22.0"
tqdm = "^4.32.2"
torch = "^1.2.0"
tokenizers = "^0.7.0"
tensorboard = "^1.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by ilovefreesw** [comment]
Facing the same thing today.
![image](https://user-images.githubusercontent.com/77317006/206459458-4bc3b27c-c340-46e9-9bb5-5b803078a836.png)

**Comment by casheo** [comment]
Same thing today 
![image](https://user-images.githubusercontent.com/60907715/208721439-802fae1e-53b3-476d-9c56-b61df9667a12.png)

With transformer 2.9.1.

**Comment by NeyokiCat** [comment]
Python3.10.10; transformers==4.26.1; tokenizers==0.13.2
Same with me: 
![微信图片_20230304195849](https://user-images.githubusercontent.com/77333688/222899827-d77739c5-b4ad-4e9e-907a-c76b6b062f4c.png)

**Comment by niranjanakella** [comment]
I am also facing the same issue can someone please kindly address this.

**Comment by AshfakYeafi** [comment]
transformers==4.24.0 and  tokenizers==0.13.2  solves the issue.
